[package]
name = "marcup"
version = "0.1.0"
authors = ["seancarroll"]
description = "Markup parser AST generator"
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
